### PR TITLE
[DOCS] Add Prometheus + Dynatrace Metric Output Instructions

### PR DESCRIPTION
**Pull request by agardnerIT**
This PR adds a new page with instructions and boilerplate code.

1. How to push metrics to Prometheus via PushGateway
2. How to push metrics to Dynatrace (coming soon as a separate PR)

### CODE REVIEW

**Comment by agardnerIT** [comment]
@vadasambar would you like to include sumo logic here?

**Comment by agardnerIT** [comment]
> I'm not sure what this is for? Why would we want to push prometheus metrics from job executor service?

Primarily for a quality gate integration. I run tool X (eg. infracost) and it provides a JSON output with metrics. I want to use those metrics in a quality gate.

**Comment by vadasambar** [comment]
> @vadasambar would you like to include sumo logic here?

Need to confirm this but I think both Datadog and Sumo support injecting Prometheus style metrics. Might be a good idea to have an issue around this so we can go ahead and merge this PR.

**Comment by agardnerIT** [comment]
Hi Christian. I thought I'd already responded but it seems to have vanished.

Eloquently put and I now agree with you. Totally understand that you don't want to take ownership of "third party code".

Do you think this belongs on the artifacthub listing or would it make more sense in a keptn-sandbox / keptn-contrib repo?

For now I'll hold a record of it here (a repo where I'm collating integration samples as my "quick go-to") until we figure out where this lives permanently: https://github.com/agardnerIT/keptn-integration-boilerplate

**Comment by agardnerIT** [comment]
Closing this as I've created: https://github.com/agardnerIT/jes-metric-exporter

It is ready to transfer to `keptn-contrib` or `keptn-sandbox` whenever you're ready.

**Comment by christian-kreuzberger-dtx** [comment]
I totally support that this could live in keptn-sandbox (and contrib at some point). Transfering those things will be done by @oleg-nenashev. If you want, you can create a PR and link to your jes-metric-exporter within job-executor.

**Pull request closed without merging**
